export const FORM_FIELDS = {
  basic: [
    { key: 'gid', label: 'GID', type: 'number', disabled: true },
    { key: 'property_id', label: 'PROPERTY ID', type: 'text', disabled: true },
    { key: 'status', label: 'STATUS', type: 'select', options: ['active', 'inactive', 'activelisting'] },
  ],
  location: [
    { key: 'situs_addr', label: 'ADDRESS', type: 'text', fullWidth: true },
    { key: 'county', label: 'COUNTY', type: 'text' },
    { key: 'city', label: 'CITY', type: 'text' },
    { key: 'latitude', label: 'LATITUDE', type: 'number', step: '0.000001' },
    { key: 'longitude', label: 'LONGITUDE', type: 'number', step: '0.000001' },
  ],
  details: [
    { key: 'acreage', label: 'ACREAGE', type: 'number', step: '0.01' },
  ],
  pricing: [
    { key: 'sell_price', label: 'PRICE', type: 'number', step: '0.01' },
    { key: 'price_per_acre', label: 'PRICE PER ACRE', type: 'number', step: '0.01' },
  ],
  contacts: [
    { key: 'seller_name', label: 'AGENT NAME', type: 'text' },
  ],
  metadata: [
    { key: 'created_at', label: 'CREATED AT', type: 'text', disabled: true },
    { key: 'updated_at', label: 'UPDATED AT', type: 'text', disabled: true },
    { key: 'analysis.meta.batch_id', label: 'BATCH ID', type: 'text', disabled: true },
    { key: 'analysis.meta.processing_mode', label: 'PROCESSING MODE', type: 'text', disabled: true },
    { key: 'analysis.meta.execution_time_seconds', label: 'EXECUTION TIME (s)', type: 'number', disabled: true },
  ],
  images: [
    { key: 'analysis.image_url', label: 'AERIAL IMAGE URL', type: 'url', fullWidth: true },
    { key: 'analysis.contour_image_url', label: 'CONTOUR IMAGE URL', type: 'url', fullWidth: true },
    { key: 'analysis.flood_image_url', label: 'FLOOD IMAGE URL', type: 'url', fullWidth: true },
    { key: 'analysis.road_frontage_image_url', label: 'ROAD FRONTAGE IMAGE URL', type: 'url', fullWidth: true },
    { key: 'analysis.tree_image_url', label: 'TREE IMAGE URL', type: 'url', fullWidth: true },
    { key: 'analysis.water_image_url', label: 'WATER IMAGE URL', type: 'url', fullWidth: true },
  ],
  parcel: [
    { key: 'analysis.parcels.geo_id', label: 'GEO ID', type: 'text', disabled: true },
    { key: 'analysis.parcels.prop_id', label: 'PARCEL PROP ID', type: 'text', disabled: true },
    { key: 'analysis.parcels.owner_name', label: 'OWNER NAME', type: 'text', disabled: true },
    { key: 'analysis.parcels.acreage', label: 'PARCEL ACREAGE', type: 'number', disabled: true },
    { key: 'analysis.parcels.situs_addr', label: 'PARCEL ADDRESS', type: 'text', disabled: true, fullWidth: true },
  ],
  sourceData: [
    { key: 'source_data.AgentName', label: 'AGENT NAME', type: 'text' },
    { key: 'source_data.AgentEmail', label: 'AGENT EMAIL', type: 'email' },
    { key: 'source_data.AgentPhone', label: 'AGENT PHONE', type: 'tel' },
    { key: 'source_data.AgentOffice', label: 'AGENT OFFICE', type: 'text' },
    { key: 'source_data.DaysOnMarket', label: 'DAYS ON MARKET', type: 'number' },
    { key: 'source_data.Beds', label: 'BEDROOMS', type: 'text' },
    { key: 'source_data.Baths', label: 'BATHROOMS', type: 'text' },
    { key: 'source_data.BuiltIn', label: 'YEAR BUILT', type: 'number' },
    { key: 'source_data.LotSize', label: 'LOT SIZE (sq ft)', type: 'number' },
    { key: 'source_data.FloorSize', label: 'FLOOR SIZE', type: 'text' },
    { key: 'source_data.Type', label: 'PROPERTY TYPE', type: 'text' },
    { key: 'source_data.State', label: 'STATE', type: 'text' },
    { key: 'source_data.Zip', label: 'ZIP CODE', type: 'number' },
  ],
  owner: [
    { key: 'source_data.PartyOwner1NameFull', label: 'OWNER 1 NAME', type: 'text', disabled: true },
    { key: 'source_data.PartyOwner2NameFull', label: 'OWNER 2 NAME', type: 'text', disabled: true },
    { key: 'source_data.PartyOwner3NameFull', label: 'OWNER 3 NAME', type: 'text', disabled: true },
    { key: 'source_data.ContactOwnerMailAddressFull', label: 'OWNER MAIL ADDRESS', type: 'text', fullWidth: true, disabled: true },
    { key: 'source_data.ContactOwnerMailAddressCity', label: 'OWNER MAIL CITY', type: 'text', disabled: true },
    { key: 'source_data.ContactOwnerMailAddressState', label: 'OWNER MAIL STATE', type: 'text', disabled: true },
    { key: 'source_data.ContactOwnerMailAddressZIP', label: 'OWNER MAIL ZIP', type: 'number', disabled: true },
  ],
  // Analysis summary fields (read-only display of complex objects)
  analysisSummary: [
    { key: 'analysis.buildable_area.buildable_acres', label: 'BUILDABLE ACRES', type: 'number', disabled: true },
    { key: 'analysis.buildable_area.buildable_percentage', label: 'BUILDABLE %', type: 'number', disabled: true },
    { key: 'analysis.flood_hazard.flood_zone_summary', label: 'FLOOD ZONE', type: 'text', disabled: true },
    { key: 'analysis.flood_hazard.total_flood_acres', label: 'FLOOD ACRES', type: 'number', disabled: true },
    { key: 'analysis.tree_coverage.tree_percentage', label: 'TREE COVERAGE %', type: 'number', disabled: true },
    { key: 'analysis.tree_coverage.brush_percentage', label: 'BRUSH %', type: 'number', disabled: true },
    { key: 'analysis.elevation_change.elevation_change_feet', label: 'ELEVATION CHANGE (ft)', type: 'number', disabled: true },
    { key: 'analysis.elevation_change.min_elevation_feet', label: 'MIN ELEVATION (ft)', type: 'number', disabled: true },
    { key: 'analysis.elevation_change.max_elevation_feet', label: 'MAX ELEVATION (ft)', type: 'number', disabled: true },
    { key: 'analysis.road_analysis.length_ft', label: 'ROAD FRONTAGE (ft)', type: 'number', disabled: true },
    { key: 'analysis.road_analysis.road_access_count', label: 'ROAD ACCESS COUNT', type: 'number', disabled: true },
    { key: 'analysis.electric_lines.intersects', label: 'ELECTRIC INTERSECTS', type: 'checkbox', disabled: true },
    { key: 'analysis.gas_lines.intersects', label: 'GAS INTERSECTS', type: 'checkbox', disabled: true },
    { key: 'analysis.well_analysis.count', label: 'WELL COUNT', type: 'number', disabled: true },
    { key: 'analysis.wetland_analysis.intersects', label: 'WETLAND INTERSECTS', type: 'checkbox', disabled: true },
    { key: 'analysis.wetland_analysis.cleared_percentage', label: 'WETLAND CLEARED %', type: 'number', disabled: true },
    { key: 'analysis.lake_analysis.unique_lake_count', label: 'LAKE COUNT', type: 'number', disabled: true },
    { key: 'analysis.pond_analysis.unique_pond_count', label: 'POND COUNT', type: 'number', disabled: true },
    { key: 'analysis.stream_intersection.intersects', label: 'STREAM INTERSECTS', type: 'checkbox', disabled: true },
    { key: 'analysis.stream_intersection.stream_length_ft', label: 'STREAM LENGTH (ft)', type: 'number', disabled: true },
  ],
}

